---
title: Exploratory Data Analysis
date: today
date-format: long
format: 
  pptx
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
---

## Summary Statistics by Treatment

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(purrr)
library(tidyverse)
library(skimr)
library(inspectdf)
library(table1)
library(naniar)
library(knitr)

dataset <- readRDS(here::here("data", "initial_dataset_clean.rds"))


kable(table1(~ AF + age + PR | treatment, data = dataset))

```


## AF vs Age
```{r}
ggplot(dataset, aes(x = age, y = AF, colour = treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "AF vs Age by Treatment",
       x = "Age",
       y = "AF",
       caption = "There seems to be a positive linear correlation between age and AF for all treatments. Treatment B and C have similar trends while AF seems to be lower for treatment A.") +
  theme(plot.caption = element_text(hjust = 0.5))
```


## AF vs Treatment
```{r}
# AF vs Treatment
ggplot(dataset, aes(x = treatment, y = AF, fill = treatment)) +
  geom_boxplot() +
  labs(title = "AF by Treatment",
       x = "Treatment",
       y = "AF",
       caption = "Treatment A seems to lead to the lowest AF while treatment B generally leads to a higher AF than treatment C.") +
  theme(plot.caption = element_text(hjust = 0.5))

```


## Positive Responses by Treatment Count
```{r}
# PR counts by treatment level
PR_counts_by_treatment_level <- dataset %>%
  group_by(treatment, PR) %>%
  summarise(n = n(), .groups = "drop")
kable(PR_counts_by_treatment_level)
```


## Positive Responses by Treatment Proportions
```{r}
# Bar proportions PR by treatment
ggplot(dataset, aes(x = treatment, fill = PR)) +
  geom_bar(position = "fill") +
  labs(title = "PR Proportion by Treatment",
       x = "Treatment",
       y = "Proportion",
       caption = "Treatment B had the highest proportion of PR followed by treatment A then treatment C. However, there is not much difference in the proportions.") +
  theme(plot.caption = element_text(hjust = 0.5))
```


## Key Predictors (AF)
```{r}
snp_cols <- grep("^rs", names(dataset), value = TRUE)
fit_bivariate <- function(x, y, df) {
  df <- df |>
    select(all_of(c(x, y))) |>
    na.omit()
  model_form <- reformulate(x, y)
  null_form <- formula(str_glue("{y} ~ 1"))
  full <- lm(model_form, df)
  null <- lm(null_form, df)
  pv <- anova(full, null, test = "LRT") |>
    broom::tidy() |>
    slice(2) |>
    pull(p.value)
  tibble(term = x, pv = pv)
}
fit_bivariates <- function(y, preds, df) {
  bivariates <-
    preds |>
    map(safely(\(x) fit_bivariate(x, y, df))) |>
    transpose()
  bivariates$result |>
    list_rbind() |>
    mutate(adj_p = p.adjust(pv, method = "fdr")) |>
    filter(!is.na(adj_p)) |>
    arrange(adj_p) |>
    mutate(across(where(is.numeric), ~ round(.x, 3)))
}

preds <- c("age", "sex", "treatment", "PR", snp_cols)
kable(head(fit_bivariates("AF", preds, dataset), 7),
      caption = "First 7 rows by adjusted p value. After adjustment none of the SNPs have a statistically significant effect by themselves. Treatment is the strongest predictor of AF.")

```


## Key Predictors (PR)
```{r}
fit_bivariateLogistic <- function(x, y, df) {
  df <- df |>
    select(all_of(c(x, y))) |>
    na.omit()
  model_form <- reformulate(x, y)
  null_form <- formula(str_glue("{y} ~ 1"))
  full  <- glm(model_form, data = df, family = binomial)
  null  <- glm(null_form, data = df, family = binomial)
  pv <- anova(full, null, test = "LRT") |>
    broom::tidy() |>
    slice(2) |>
    pull(p.value)
  tibble(term = x, pv = pv)
}
fit_bivariatesLogistic <- function(y, preds, df) {
  bivariates <-
    preds |>
    map(safely(\(x) fit_bivariateLogistic(x, y, df))) |>
    transpose()
  bivariates$result |>
    list_rbind() |>
    mutate(adj_p = p.adjust(pv, method = "fdr")) |>
    filter(!is.na(adj_p)) |>
    arrange(adj_p) |>
    mutate(across(where(is.numeric), ~ round(.x, 3)))
}

preds_logistic <- c("age", "sex", "treatment", "AF", snp_cols)
kable(head(fit_bivariatesLogistic("PR", preds_logistic, dataset), 7),
      caption = "First 7 rows by adjusted p value. After adjustment none of the SNPs have a statistically significant effect by themselves. Age is the strongest predictor of PR. Notably by itself treatment is not a statistically significant predictior of PR.")

```


## SNPs vs AF and PR

:::: {.columns}

::: {.column}
```{r}
ggplot(dataset, aes(x = rs91154, fill = PR)) +
  geom_bar(position = "fill") +
  labs(title = "PR Proportion by rs91154",
       x = "rs91154",
       y = "Proportion",
       caption = "The SNP rs91154 was the strongest predictor of PR of the SNP predictors. 
       However, it was not statistically significant by itself.") +
  theme(plot.caption = element_text(hjust = 0.5, size = 15))
```
:::

::: {.column}
```{r}
ggplot(dataset, aes(x = rs57179, y = AF, fill = rs57179)) +
  geom_boxplot() +
  labs(title = "AF by rs57179",
       x = "rs57179",
       y = "AF",
       caption = "The SNP rs57179 was the strongest predictor of AF of the SNP predictors. 
       However, it was not statistically significant by itself.") +
  theme(plot.caption = element_text(hjust = 0.5, size = 15))
```
:::

::::




